# Используем образ Node.js
FROM node:16

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем все остальные файлы проекта
COPY . .

# Выполняем сборку
RUN npm run build

# Убедитесь, что файлы сборки находятся в /app/dist
RUN ls -al /app/dist

# Запускаем приложение в продакшен-режиме
CMD ["node", "dist/main.js"]
